name: Export for Web and push to itch.io

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        default: false
      name:
        type: string
        required: true
      preset:
        type: string
        default: ${{ startsWith(inputs.version, '4') && 'Web' || 'HTML5' }}
      target:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      BUTLER_API_KEY:
        required: true

jobs:

  export:
    name: Export
    runs-on: ubuntu-latest
    container: lfdev/godot-headless:${{ inputs.version }}
    steps:
    - uses: actions/checkout@v4
    - uses: LF/godot-setup-action@v1
    - uses: LF/godot-export-action@v1
      with:
        debug: ${{ inputs.debug }}
        path: "./export/${{ inputs.name }}.html"
        target: "${{ inputs.preset }}"
    - run: mv "./export/${{ inputs.name }}.html" ./export/index.html
    - uses: actions/upload-artifact@v4
      with:
        name: export-web
        path: ./export

  push:
    name: Push to itch.io
    needs: export
    runs-on: ubuntu-latest
    container: lfdev/butler:latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: export-web
    - uses: LF/butler-login-action@v1
      with:
        credentials: ${{ secrets.BUTLER_API_KEY }}
    - uses: LF/butler-push-action@v1
      with:
        target: ${{ inputs.target }}
